# Generated by Django 4.0.5 on 2022-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_listing_bid_price_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="Image URL"),
        ),
    ]
