# Generated by Django 4.0.5 on 2022-06-15 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Starting Bid",
            ),
        ),
    ]
