# Generated by Django 4.0.5 on 2022-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("MA", "Men's Apparel"),
                    ("MBA", "Men's Bags & Accessories"),
                    ("MS", "Men's Shoes"),
                    ("WB", "Women's Bags"),
                    ("WAC", "Women's Accessories"),
                    ("WAP", "Women's Apparel"),
                    ("WS", "Women's Shoes"),
                    ("HPC", "Health & Personal Care"),
                    ("MF", "Makeup & Fragrances"),
                    ("CA", "Cameras"),
                    ("MOG", "Mobiles & Gadgets"),
                    ("MOA", "Mobile Accessories"),
                    ("LC", "Laptops & Computers"),
                    ("AUD", "Audio"),
                    ("GAM", "Gaming"),
                    ("DGV", "Digital Goods & Vouchers"),
                    ("HA", "Home Appliances"),
                    ("HE", "Home Entertainment"),
                    ("HL", "Home & Living"),
                    ("GRO", "Groceries"),
                    ("BK", "Babies & Kids"),
                    ("TGC", "Toys, Games & Collectibles"),
                    ("MO", "Motors"),
                    ("ST", "Sports & Travel"),
                    ("PET", "Pet Care"),
                    ("OT", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
