# Generated by Django 4.0.5 on 2022-06-15 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Men's-Apparel", "Men's Apparel"),
                    ("Men's-Bags-Accessories", "Men's Bags & Accessories"),
                    ("Men's-Shoes", "Men's Shoes"),
                    ("Women's-Bags", "Women's Bags"),
                    ("Women's-Accessories", "Women's Accessories"),
                    ("Women's-Apparel", "Women's Apparel"),
                    ("Women's-Shoes", "Women's Shoes"),
                    ("Health-Personal-Care", "Health & Personal Care"),
                    ("Makeup-Frargances", "Makeup & Fragrances"),
                    ("Cameras", "Cameras"),
                    ("Mobiles-Gadgets", "Mobiles & Gadgets"),
                    ("Mobile-Accessories", "Mobile Accessories"),
                    ("Laptops-Computers", "Laptops & Computers"),
                    ("Audio", "Audio"),
                    ("Gaming", "Gaming"),
                    ("Digital-Goods-Vouchers", "Digital Goods & Vouchers"),
                    ("Home-Appliances", "Home Appliances"),
                    ("Home-Entertainment", "Home Entertainment"),
                    ("Home-Living", "Home & Living"),
                    ("Groceries", "Groceries"),
                    ("Babies-Kids", "Babies & Kids"),
                    ("Toys-Games-Collectibles", "Toys, Games & Collectibles"),
                    ("Motors", "Motors"),
                    ("Sports-Travel", "Sports & Travel"),
                    ("Pet-Care", "Pet Care"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listings", models.ManyToManyField(blank=True, to="auctions.listing")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
