# Generated by Django 4.0.5 on 2022-06-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_bid_bid_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
    ]
