# Generated by Django 4.0.5 on 2022-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_bid_date_created_remove_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
